import {writeFile,mkdir} from 'node:fs/promises';
import {site,projects} from './content.mjs';
const out=new URL('../public/',import.meta.url);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const nav=[['work.html','Work'],['services.html','Services'],['studio.html','Studio'],['contact.html','Contact']];
const img=(p,cls='',eager=false)=>`<img class="${cls}" src="assets/${p.image}.webp" alt="${esc(p.alt)}" width="1536" height="961" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const card=(p,i)=>`<article class="project-card" data-category="${p.category}"><a href="project-${p.slug}.html">${img(p)}<div class="card-meta"><span class="index">0${i+1}</span><div><h2>${p.name}</h2><p>${p.summary}</p></div><span class="card-arrow" aria-hidden="true">↗</span></div></a><span class="tag">${p.place} / Concept study</span></article>`;
function page(file,title,description,body){
const current=file.startsWith('project-')?'work.html':file;
return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — FORMA Atelier</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f6f5f0"><link rel="canonical" href="${site.url}/${file==='index.html'?'':file.replace('.html','')}"><meta property="og:title" content="${esc(title)} — FORMA Atelier"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${site.url}/${file==='index.html'?'':file.replace('.html','')}"><meta property="og:image" content="${site.url}/assets/coastal-house.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><script src="assets/app.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="FORMA Atelier home">FORMA<span>ATELIER</span></a><span class="header-note">Architecture &amp; interiors<br>A studio website concept</span><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu <span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}" ${url===current?'aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header>
<main id="main">${body}</main>
<footer class="footer"><div class="wrap"><div class="footer-top"><a class="brand" href="index.html">FORMA<span>ATELIER</span></a><p>An architecture studio, imagined.<br>A website built to be explored.</p><a class="text-link" href="https://nevquo.com/">A project by NEVQUO ↗</a></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} NEVQUO · Independent concept</span><a href="project-notes.html">Project notes &amp; image credits</a><a href="privacy.html">Privacy</a></div></div></footer></body></html>`;
}
const intro=(label,title,copy)=>`<section class="wrap page-intro"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="lead">${copy}</p></section>`;
const cta=`<section class="wrap cta"><p class="eyebrow">From looking to talking</p><h2>Have a website<br>in mind?</h2><div><p>FORMA is a concept. NEVQUO is where you can discuss a real design or development project.</p><a class="button" href="contact.html">Contact NEVQUO <span aria-hidden="true">↗</span></a></div></section>`;
const pages={};
pages['index.html']=page('index.html','Rooms for everyday life','An independent architecture-studio website concept by NEVQUO. Explore five studies in homes, interiors and hospitality.',`
<section class="wrap home-intro"><p class="eyebrow">FORMA / Architecture &amp; interiors</p><div class="hero-heading"><h1>Rooms for<br>everyday life.</h1><div><p>A place to come home to. A table in good light. A shaded spot at the end of the day.</p><p class="muted">Five studies in how buildings can make room for ordinary things.</p><a class="text-link" href="work.html">Explore the studies <span aria-hidden="true">↘</span></a></div></div></section>
<figure class="wrap hero-image"><a href="project-casa-serein.html">${img(projects[0],'',true)}</a><figcaption><span>01 / Casa Serein</span><span>Coastal home · Concept visualisation</span><a href="project-casa-serein.html">View study ↗</a></figcaption></figure>
<section class="wrap section split"><div><p class="eyebrow">The starting point</p><h2>A building is more<br>than its best view.</h2></div><div class="prose"><p>It is also the route from the door to the kitchen, the storage that keeps a room useful, and the window you open each morning.</p><p>These studies begin with those small decisions. Each looks at a different setting, with a short brief, a few design choices and a clear account of what has—and has not—been resolved.</p><a class="text-link" href="studio.html">About the concept ↗</a></div></section>
<section class="wrap section"><div class="section-title"><div><p class="eyebrow">A closer look</p><h2>Two different starting points.</h2></div><a class="text-link" href="work.html">All five studies ↗</a></div><div class="project-grid">${card(projects[1],1)}${card(projects[3],3)}</div></section>
<section class="wrap section"><div class="section-title"><div><p class="eyebrow">Areas of practice / Illustrative</p><h2>From a room to a whole building.</h2></div><a class="text-link" href="services.html">Scope &amp; process ↗</a></div><div class="service-grid"><article><span class="index">01</span><h3>Homes</h3><p>Layouts, thresholds and outdoor spaces that work together.</p></article><article><span class="index">02</span><h3>Interiors</h3><p>Storage, materials and lighting considered around daily use.</p></article><article><span class="index">03</span><h3>Small hospitality</h3><p>Guest spaces planned alongside the work of running them.</p></article></div></section>${cta}`);
pages['work.html']=page('work.html','Work','Five clearly labelled concept studies, each with its own brief and design decisions.',`${intro('Index / 01–05','Five studies.<br>Different ways to live.','Homes, interiors and a small retreat. These are imagined briefs, not completed commissions.')}<section class="wrap section work-section"><div class="filters" aria-label="Filter studies" hidden>${['All','Homes','Interiors','Hospitality'].map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}<span id="result-count" role="status">5 studies</span></div><div class="project-grid">${projects.map(card).join('')}</div></section>${cta}`);
for(const [i,p] of projects.entries()){
 const next=projects[(i+1)%projects.length];
 pages[`project-${p.slug}.html`]=page(`project-${p.slug}.html`,p.name,p.summary,`<section class="wrap project-intro"><a class="text-link" href="work.html">← All studies</a><div class="project-title"><h1>${p.name}</h1><p>${p.summary}</p></div><div class="project-facts"><span>${p.place}</span><span>Independent concept study</span><span>0${i+1} / 05</span></div></section><figure class="wrap project-image">${img(p,'',true)}<figcaption>Concept visualisation · Not a photograph of a built project</figcaption></figure><section class="wrap section split"><div><p class="eyebrow">The brief</p><h2>${p.question}</h2></div><div class="prose"><p>${p.brief}</p></div></section><section class="wrap section"><p class="eyebrow">Three decisions</p><div class="decision-list">${p.decisions.map(([t,c],j)=>`<article><span class="index">0${j+1}</span><h3>${t}</h3><p>${c}</p></article>`).join('')}</div><aside class="study-note"><strong>What remains to be tested</strong><p>${p.note}</p></aside></section><section class="wrap next-study"><span class="eyebrow">Next study</span><a href="project-${next.slug}.html"><h2>${next.name}</h2><span aria-hidden="true">↗</span></a></section>`);
}
pages['services.html']=page('services.html','Scope & process','An illustrative architecture-studio service structure, from the first brief to design development.',`${intro('Scope & process','Start with the brief.<br>Then decide the scope.','A single room and a new building need different kinds of work. This page illustrates how a studio could make those boundaries clear.')}<section class="wrap section"><p class="notice-inline">FORMA is not an operating architectural practice. The services below demonstrate the website’s content and enquiry structure.</p>${[
['01','New homes','For a brief that starts with a site.','Site questions, room relationships, initial options and a developing material direction. A real appointment would also define consultant roles, approvals and technical deliverables.','Not assumed: planning consent, engineering or construction management.'],
['02','Interiors & renovation','For spaces that need to work differently.','A review of the existing layout, storage needs, lighting and finishes. Early decisions focus on what can stay, what needs to change and how the work might be phased.','Not assumed: structural alterations or a contractor’s price.'],
['03','Small hospitality','For a guest experience with practical demands.','Arrival, shared spaces, rooms and outdoor routes considered alongside servicing, cleaning and maintenance. The operational brief informs the design from the start.','Not assumed: licensing, operator strategy or statutory approvals.']
].map(([n,t,s,c,b])=>`<article class="service-detail"><span class="index">${n}</span><div><h2>${t}</h2><p class="lead-small">${s}</p></div><div class="prose"><p>${c}</p><p class="muted">${b}</p></div></article>`).join('')}</section><section class="wrap section split"><div><p class="eyebrow">An example process</p><h2>Make the next<br>decision clear.</h2></div><div class="steps">${[['Listen','Establish the needs, constraints and people involved. Write down what success would mean.'],['Explore','Compare a small number of options. Explain the compromises, not just the preferred image.'],['Develop','Resolve the chosen direction with the relevant specialists. Keep a record of decisions.'],['Review','Check the work against the brief, budget and practical requirements before proceeding.']].map(([a,b],i)=>`<article><span>0${i+1}</span><div><h3>${a}</h3><p>${b}</p></div></article>`).join('')}</div></section><section class="wrap section faq"><p class="eyebrow">Before getting in touch</p><h2>A few useful answers.</h2><details><summary>Can I commission FORMA to design a building?</summary><p>No. FORMA is an independent website concept, not a registered practice. For a real building project, consult an appropriately qualified local professional.</p></details><details><summary>What should a first enquiry include?</summary><p>The place or website you want to change, the problem you want to solve, an approximate budget and any important dates. A short, clear note is enough to start.</p></details><details><summary>Can NEVQUO create a site like this for my business?</summary><p>Yes, you can discuss a website project with NEVQUO. Use the contact page to send an enquiry or visit nevquo.com.</p></details></section>${cta}`);
pages['studio.html']=page('studio.html','The studio concept','Why FORMA exists, what the project demonstrates, and where the concept ends.',`${intro('About FORMA','A studio, imagined.<br>A website, built.','FORMA Atelier is an independent portfolio project by NEVQUO. It explores how a small design practice can present its work without burying it in sales language.')}<section class="wrap section split"><div><p class="eyebrow">Why this project</p><h2>Let the work<br>do more of the talking.</h2></div><div class="prose"><p>A studio website has a straightforward job: help someone understand the work, find the relevant experience and decide whether to get in touch.</p><p>This concept uses a small project index, readable study pages and a clearly scoped services page. There are no invented awards, team biographies or client testimonials.</p><p>The architectural studies are a framework for demonstrating the website. They are not evidence of architectural commissions undertaken by NEVQUO.</p></div></section><section class="wrap section"><p class="eyebrow">Principles behind the site</p><div class="service-grid"><article><span class="index">01</span><h3>Specific beats grand</h3><p>Explain a decision, its purpose and its limits. Leave claims about excellence to the reader.</p></article><article><span class="index">02</span><h3>Less, but useful</h3><p>One relevant image and a clear brief tell more than a gallery of repeated views.</p></article><article><span class="index">03</span><h3>Make it easy to use</h3><p>Readable text, predictable navigation and a form that tells people what happens next.</p></article></div></section><section class="wrap section split"><h2>About the imagery.</h2><div class="prose"><p>The images were generated for the original concept. They are retained here as visual studies and labelled accordingly; they are not site photographs.</p><p>For a commissioned studio website, these would be replaced by licensed project photography, drawings and client-approved descriptions.</p><a class="text-link" href="project-notes.html">Read the project notes ↗</a></div></section>${cta}`);
pages['contact.html']=page('contact.html','Contact','Contact NEVQUO about a website project or send feedback on the FORMA concept.',`${intro('Contact NEVQUO','Tell us what<br>you’re working on.','For a website project, a question about this concept, or feedback on something that could work better.')}<section class="wrap section contact-grid"><div class="contact-aside"><p class="eyebrow">A real point of contact</p><a class="email-link" href="mailto:${site.email}">${site.email}</a><p>FORMA is a demonstration site. Messages go to NEVQUO, not an architecture studio.</p><p>Please do not send confidential drawings, passwords or payment details.</p><a class="text-link" href="https://nevquo.com/">Visit NEVQUO ↗</a></div><form id="inquiry-form"><h2>A short note is enough.</h2><p id="form-status" role="status">Checking the enquiry service… You can always use the email link.</p><noscript><p>JavaScript is needed for this form. Please use the email link instead.</p></noscript><fieldset id="form-fields" disabled><div class="form-row"><label>Your name <span>(required)</span><input name="name" autocomplete="name" required maxlength="120"></label><label>Email <span>(required)</span><input name="email" type="email" autocomplete="email" required maxlength="190"></label></div><label>What is this about?<select name="type"><option>Website project</option><option>Concept feedback</option><option>Other question</option></select></label><label>Your message <span>(required)</span><textarea name="message" required minlength="10" maxlength="4000" rows="6" placeholder="What would you like to make or improve?"></textarea></label><div class="honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent"><input type="checkbox" name="consent" required><span>I agree that NEVQUO may store this message and use my email to respond. <a href="privacy.html">Privacy details</a></span></label><div id="turnstile"></div><button class="button" type="submit">Send enquiry <span aria-hidden="true">↗</span></button><p class="small">After a successful submission, you’ll receive a reference on this page. No automatic email is sent.</p></fieldset><p id="form-result" role="status" aria-live="polite" tabindex="-1"></p></form></section>`);
pages['privacy.html']=page('privacy.html','Privacy','How enquiries through this FORMA concept website are handled.',`${intro('Privacy','Your message.<br>Only what is needed.','This concept website is operated by NEVQUO.')}<section class="wrap section narrow prose"><h2>What the form collects</h2><p>When enabled, the form stores your name, email, topic, message, consent and submission date in Cloudflare D1. It returns a reference so you can identify the enquiry later.</p><h2>Why it is collected</h2><p>NEVQUO uses these details to review and respond to your enquiry. Please avoid sensitive personal information. This form does not subscribe you to marketing emails.</p><h2>Spam protection</h2><p>The enabled form uses Cloudflare Turnstile. Your browser contacts Cloudflare to perform a security check. The application does not store your IP address in its enquiry database.</p><h2>Access and retention</h2><p>Enquiries are available to the site operator through the Cloudflare account. NEVQUO should delete resolved enquiries when they are no longer needed. To ask about your information or request deletion, email <a href="mailto:${site.email}">${site.email}</a> and include your enquiry reference if you have it.</p><h2>Other browsing data</h2><p>This package does not install advertising trackers or analytics. The hosting provider may process request information to operate and protect the service.</p><h2>Email instead</h2><p>If you use the email link, your message is handled by your email provider and NEVQUO’s mailbox provider rather than this form.</p></section>`);
pages['project-notes.html']=page('project-notes.html','Project notes','Credits and boundaries for the FORMA Atelier concept website.',`${intro('Credits & context','What this project is.<br>And what it isn’t.','An independent web-design and development concept for the NEVQUO portfolio.')}<section class="wrap section narrow prose"><h2>The business and the studies</h2><p>FORMA Atelier is an imagined studio. The five project names, briefs and proposed design decisions are illustrative. They do not represent commissioned or completed architecture.</p><h2>Images</h2><p>The five architectural visualisations were AI-generated for this concept. They are not photographs of buildings designed by NEVQUO. No real client endorsement is implied.</p><h2>How the website was made</h2><p>This is an AI-assisted website project developed for NEVQUO. Its content and implementation should be reviewed and approved by the owner before publication. It is not presented as work created without AI assistance.</p><h2>What to evaluate</h2><p>The information structure, visual design, responsive layouts, project filtering, keyboard navigation and enquiry workflow. Any live performance or accessibility claims should be supported by tests on the published version.</p><h2>Contact</h2><p>For questions about the site or its use, contact <a href="mailto:${site.email}">${site.email}</a>.</p></section>`);
pages['404.html']=page('404.html','Page not found','The requested page could not be found.',`${intro('404 / Page not found','That page<br>isn’t here.','The link may be old, or the address may have changed.')}<section class="wrap section"><a class="button" href="/index.html">Back to the homepage ↗</a></section>`).replaceAll('href="assets/','href="/assets/').replaceAll('src="assets/','src="/assets/');
await mkdir(out,{recursive:true});
for(const [file,html] of Object.entries(pages))await writeFile(new URL(file,out),file==='404.html'?html.replace(/href="(?!https?:|mailto:|#|\/)([^"]+)"/g,'href="/$1"'):html);
await writeFile(new URL('robots.txt',out),`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).filter(x=>x!=='404.html').map(x=>`<url><loc>${site.url}/${x==='index.html'?'':x.replace('.html','')}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${Object.keys(pages).length} pages.`);
